services:

  mongo:
    image: mongo:7
    restart: unless-stopped
    volumes:
      - mongo_data:/data/db

  backend:
    build:
      context: ./BACKEND
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "5000:5000"
    env_file:
      - ./BACKEND/.env
    depends_on:
      - mongo

  frontend:
    build:
      context: ./FRONTEND
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  mongo_data:

networks:
  default:
    driver: bridge
